In [ ]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load Dataset
ethnic = pd.read_csv("/content/drive/MyDrive/GitHub/4_Machine_Learning/2_Data_Preprocessing_&_Normalization/modified_ethnic.csv")

In [ ]:
ethnic.columns

Index(['Position', 'State', 'Sex', 'MaritalDesc', 'CitizenDesc',
       'EmploymentStatus', 'Department', 'Salaries', 'age', 'Race'],
      dtype='object')

In [ ]:
ethnic.head()

,Position,State,Sex,MaritalDesc,CitizenDesc,EmploymentStatus,Department,Salaries,age,Race
0,Accountant I,NaN,F,Married,US Citizen,Active,Admin Offices,674.28,NaN,Black or African American
1,Accountant I,MA,M,Divorced,US Citizen,Active,Admin Offices,674.28,50.0,Black or African American
2,Accountant I,MA,M,Single,NaN,Active,Admin Offices,674.28,43.0,White
3,Administrative Assistant,MA,F,NaN,US Citizen,Terminated for Cause,Admin Offices,47822.00,44.0,NaN
4,NaN,MA,F,Single,US Citizen,Active,Admin Offices,NaN,33.0,White

In [ ]:
ethnic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Position          267 non-null    object
 1   State             275 non-null    object
 2   Sex               276 non-null    object
 3   MaritalDesc       281 non-null    object
 4   CitizenDesc       283 non-null    object
 5   EmploymentStatus  278 non-null    object
 6   Department        292 non-null    object
 7   Salaries          278 non-null    float64
 8   age               275 non-null    float64
 9   Race              285 non-null    object
dtypes: float64(2), object(8)
memory usage: 24.3+ KB

In [ ]:
ethnic.describe()

            Salaries         age
count     278.000000  275.000000
mean    36725.396007   38.592727
std     20997.074151    9.290994
min        75.000000   23.000000
25%     24294.772500   30.500000
50%     35568.315000   39.000000
75%     51452.895000   46.000000
max    108304.000000   54.000000

In [ ]:
ethnic.isnull().sum()

Position            43
State               35
Sex                 34
MaritalDesc         29
CitizenDesc         27
EmploymentStatus    32
Department          18
Salaries            32
age                 35
Race                25
dtype: int64

**1. Mean Imputation**

Replaces missing values with the column mean. Simple and fast but reduces variance and ignores relationships.

Use when

-> Missing completely at random (MCAR)

-> Small % of missing values

-> Baseline imputation

-> Use median for skewed features

Avoid when

Not suitable when data is missing not at random (MNAR) — creates bias.

In [ ]:
ethnic['age'].head()

0     NaN
1    50.0
2    43.0
3    44.0
4    33.0
Name: age, dtype: float64

In [ ]:
ethnic['age'] = ethnic['age'].fillna(ethnic['age'].mean(), inplace=True)

/tmp/ipykernel_3640/3886791524.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ethnic['age'] = ethnic['age'].fillna(ethnic['age'].mean(), inplace=True)

In [ ]:
ethnic['age'].head()

0    38.592727
1    50.000000
2    43.000000
3    44.000000
4    33.000000
Name: age, dtype: float64

In [ ]:
ethnic['age'].isnull().sum()

np.int64(0)

**2. Median Imputation**

Replaces missing values with the column median. Simple and fast but reduces variance and ignores relationships.

Use when

-> Missing completely at random (MCAR)

-> Small % of missing values

-> Baseline imputation

-> Use median for skewed features

Avoid when

Not suitable when data is missing not at random (MNAR) — creates bias.

In [ ]:
ethnic['Salaries'].head(-1)

0        674.280000
1        674.280000
2        674.280000
3      47822.000000
4         38.592727
           ...
304    24828.700000
305       38.592727
306    27603.000000
307    27587.460000
308    12126.530000
Name: Salaries, Length: 309, dtype: float64

In [ ]:
ethnic['Salaries'] = ethnic['Salaries'].fillna(ethnic['Salaries'].median(), inplace=True)

/tmp/ipykernel_3640/3770997471.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ethnic['Salaries'] = ethnic['Salaries'].fillna(ethnic['Salaries'].median(), inplace=True)

In [ ]:
ethnic['Salaries'].head(-1)

0        674.280000
1        674.280000
2        674.280000
3      47822.000000
4         38.592727
           ...
304    24828.700000
305       38.592727
306    27603.000000
307    27587.460000
308    12126.530000
Name: Salaries, Length: 309, dtype: float64

In [ ]:
ethnic['Salaries'].isnull().sum()

np.int64(0)

**3. Mode Imputation**

Replaces missing values with the column mode. Simple and fast but reduces variance and ignores relationships.

Use when

-> Missing completely at random (MCAR)

-> Small % of missing values

-> Baseline imputation

-> Use median for skewed features

-> Use mode for Categorical features

Avoid when

Not suitable when data is missing not at random (MNAR) — creates bias.

In [ ]:
ethnic['Sex'].head()

0    None
1    None
2    None
3    None
4    None
Name: Sex, dtype: object

In [ ]:
ethnic['Sex'] = ethnic['Sex'].fillna(ethnic['Sex'].mode()[0])
# ethnic['Sex'].fillna(ethnic['Sex].mode()[0], inplace = True) # if you want to add inplace = True

In [ ]:
ethnic['Sex'].isnull().sum()

np.int64(0)

In [ ]:
ethnic['Sex'].head()

0     F
1    M
2    M
3     F
4     F
Name: Sex, dtype: object

**4. KNN Imputation**

Finds k most similar rows and uses their values to fill the gap. More accurate than mean but computationally expensive.

Use when

-> Small-to-medium datasets

-> When relationships between features matter

-> MICE-like iterative imputation

Avoid when

Computationally expensive for large datasets. Needs feature scaling first.

In [ ]:
from sklearn.impute import KNNImputer

In [ ]:
ethnic['Salaries'].head()

0      674.28
1      674.28
2      674.28
3    47822.00
4         NaN
Name: Salaries, dtype: float64

In [ ]:
imputer = KNNImputer(n_neighbors=5)

In [ ]:
ethnic['Salaries'] = imputer.fit_transform(ethnic[['Salaries']])

In [ ]:
ethnic['Salaries'].head()

0      674.280000
1      674.280000
2      674.280000
3    47822.000000
4    36725.396007
Name: Salaries, dtype: float64

**5. Indicator + Impute**

Creates a binary flag column to indicate missingness, then imputes. Preserves the information that a value was missing.

Use when

-> When missingness itself is informative

-> Medical / survey data

-> Combined with any imputation method

Avoid when

Unnecessary if data is MCAR and you are just quickly imputing for a baseline.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.DataFrame({
    "Salary": [40000, np.nan, 50000, np.nan],
    "Loan_Approved": [True, False, True, False]
})

In [ ]:
imputer = SimpleImputer(
    strategy="mean",
    add_indicator=True
)

In [ ]:
result = imputer.fit_transform(df[['Salary']])
print(result)

[[4.0e+04 0.0e+00]
 [4.5e+04 1.0e+00]
 [5.0e+04 0.0e+00]
 [4.5e+04 1.0e+00]]